version: '3.8'
services:
  db:
    image: postgres:15
    container_name: smartspend-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartspend
    ports:
      - "5432:5432"